-- Migration: Expand stocks table with JSONB and numeric columns
-- Run: psql against Supabase
-- Status: APPLIED (columns already exist in production)

ALTER TABLE stocks ADD COLUMN IF NOT EXISTS score_composite INTEGER DEFAULT 50;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS score_subs JSONB DEFAULT '{}';
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS financials JSONB DEFAULT '[]';
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS dividends JSONB DEFAULT '[]';
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS last_price NUMERIC;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS price_change NUMERIC DEFAULT 0;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS dividend_yield NUMERIC;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pe_ratio NUMERIC;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS roe NUMERIC;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS debt_to_equity NUMERIC;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS market_cap NUMERIC;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS sparkline JSONB DEFAULT '[]';
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '';
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS revisit_at TIMESTAMPTZ;
