import React from 'react'

const Terms: React.FC = () => {
  return (
    <div className="max-w-3xl mx-auto py-12 px-4">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>

      <div className="prose prose-lg dark:prose-invert space-y-6">
        <section>
          <h2 className="text-xl font-semibold mb-3">Acceptance</h2>
          <p>
            By using Divvy, you agree to these Terms of Service. If you do not agree, do not use the platform.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Service Description</h2>
          <p>
            Divvy provides stock screening, scoring, analysis reports, and portfolio tools for Bursa Malaysia-listed
            securities. Features may change or be discontinued at any time without notice.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">User Responsibilities</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials and for all
            activity under your account. You agree not to misuse, reverse-engineer, or resell Divvy's data
            or reports without explicit permission.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Paid Services</h2>
          <p>
            Paid features (Pro subscription, one-time reports) are billed in advance and are non-refundable
            unless required by applicable law. Report download links are time-limited and for personal use only.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Intellectual Property</h2>
          <p>
            All content, analysis, scores, and reports generated by Divvy are protected by copyright.
            Redistribution without permission is prohibited.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Limitation of Liability</h2>
          <p>
            Divvy is provided "as is" without warranties of any kind. See our full Disclaimer for details
            on financial liability.
          </p>
        </section>

        <p className="text-sm text-gray-500 pt-8">
          Last updated: June 11, 2026
        </p>
      </div>
    </div>
  )
}

export default Terms
