import React from 'react'
import { Link } from 'react-router-dom'
import { Helmet } from 'react-helmet-async'
import { seo } from '../lib/seo'

const Terms: React.FC = () => {
  return (
    <>
      <Helmet {...seo({
        title: 'Terms of Service — Divvy',
        description: 'Terms of Service for Divvy. By using this platform, you agree to these terms covering usage, paid services, intellectual property, and liability limitations.',
        canonical: 'https://d2d7b6u77b6we4.cloudfront.net/terms',
      })} />
      <div className="max-w-3xl mx-auto py-12 px-4">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>

        <div className="prose prose-lg dark:prose-invert space-y-6">
          <section>
            <h2 className="text-xl font-semibold mb-3">Acceptance</h2>
            <p>
              By accessing or using Divvy ("the Platform"), you agree to be bound by these Terms of Service.
              If you do not agree with any part of these terms, you must not use the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Service Description</h2>
            <p>
              Divvy provides stock screening, scoring, AI-generated analysis reports, portfolio tracking,
              and related tools for Bursa Malaysia-listed securities. Features, scoring models, and available
              tools may change or be discontinued at any time without prior notice.
            </p>
            <p>
              The Platform is provided as a data tool — not as a financial advisory service. See our{' '}
              <Link to="/disclaimer" className="text-emerald-600 dark:text-emerald-400 underline">full Disclaimer</Link> for details.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">User Responsibilities</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You are responsible for all activity under your account, including any investment decisions you make.</li>
              <li>You agree not to misuse, scrape, reverse-engineer, or resell Divvy's data, reports, or analysis without explicit written permission.</li>
              <li>You agree not to use the Platform for any unlawful purpose or in violation of Malaysian laws or regulations.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Paid Services</h2>
            <p>
              Paid features (Pro subscription, one-time AI reports) are billed in advance and are
              <strong> non-refundable</strong> unless required by applicable law or expressly stated otherwise.
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>One-time report download links are time-limited (72 hours) and for personal use only.</li>
              <li>Pro subscriptions renew automatically unless cancelled before the renewal date.</li>
              <li>We reserve the right to modify pricing with 30 days' notice.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Intellectual Property</h2>
            <p>
              All content, analysis, scores, reports, forecasts, and code generated by or displayed on Divvy
              are protected by copyright and applicable intellectual property laws.
            </p>
            <p>
              Redistribution, reproduction, or commercial use of Divvy-generated content without explicit
              written permission is prohibited. You retain ownership of any content you submit (e.g., portfolio
              data), and grant Divvy a license to store and process it for service delivery.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Limitation of Liability</h2>
            <p>
              Divvy is provided <strong>"as is"</strong> and <strong>"as available"</strong> without
              warranties of any kind, either express or implied. To the maximum extent permitted by law,
              Divvy and its creators shall not be liable for any indirect, incidental, special, consequential,
              or punitive damages arising from your use of the Platform.
            </p>
            <p>
              See our <Link to="/disclaimer" className="text-emerald-600 dark:text-emerald-400 underline">full Disclaimer</Link> for
              specific details on financial liability and risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Governing Law</h2>
            <p>
              These terms are governed by the laws of Malaysia. Any disputes shall be resolved in the
              courts of Kuala Lumpur, Malaysia.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Changes to Terms</h2>
            <p>
              We reserve the right to update these terms at any time. Material changes will be communicated
              via email or a notice on the Platform. Continued use after changes take effect constitutes
              acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Contact</h2>
            <p>
              For questions about these terms, contact us at <strong>legal@divvy.my</strong>.
            </p>
          </section>

          <p className="text-sm text-gray-500 pt-8">
            Last updated: June 15, 2026
          </p>
        </div>

        <nav className="mt-12 pt-6 border-t border-gray-200 dark:border-gray-700 flex justify-center gap-6 text-sm">
          <Link to="/privacy" className="text-gray-500 hover:text-emerald-600 dark:text-gray-400 dark:hover:text-emerald-400">Privacy Policy</Link>
          <Link to="/disclaimer" className="text-gray-500 hover:text-emerald-600 dark:text-gray-400 dark:hover:text-emerald-400">Disclaimer</Link>
        </nav>
      </div>
    </>
  )
}

export default Terms
